FROM amazoncorretto:21-alpine-jdk
ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME

ADD build/libs/taf-mock-provider-0.0.1-SNAPSHOT.jar taf-mock-provider.jar

COPY /src/main/resources/mock-example.zip src/main/resources/mock-example.zip

EXPOSE 8082
ENTRYPOINT ["sh", "-c", "java -jar taf-mock-provider.jar"]