FROM amazoncorretto:21-alpine-jdk
ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME

ADD build/libs/taf-orchestrator-0.0.1-SNAPSHOT.jar taf-orchestrator.jar

EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java -jar taf-orchestrator.jar"]